### ISSUE TITLE
Unicode character in log.

### ISSUE THREAD

**Issue by vivekimsit** [sindresorhus/is-github-down#2]
Seems there is extra unicode character left by mistake.

``` js
console.log(`\n🦄  It's down. Go outside!`);
```

**Comment by sindresorhus** [comment]
No, I had add an extra whitespace as otherwise it would be too close to the `I` in the terminal.

**Comment by vivekimsit** [comment]
`\t` doesn't work?

**Comment by developit** [comment]
It's a unicorn

**Comment by sindresorhus** [comment]
> \t doesn't work?

No, tabs are not for alignment and would be too wide.
