### ISSUE TITLE
Needs a watcher

### ISSUE THREAD

**Issue by corysimmons** [sindresorhus/is-github-down#4]
Awesome tool btw. @sindresorhus finally produces something useful

**Comment by sindresorhus** [comment]
Your request is unclear. Can you elaborate?

**Comment by corysimmons** [comment]
`is-github-down --watch` should ping github every minute. It should remain silent after it alerts the user of a change.

``` js
$ is-github-down --watch
github is down
// 3 hours later
github is up
```

(i'd also like to mention this request is a joke)

**Comment by sindresorhus** [comment]
> (i'd also like to mention this request is a joke)

Oh, hah, that was not clear :p
