### ISSUE TITLE
non-zero exit code

### ISSUE THREAD

**Issue by wayneashleyberry** [sindresorhus/is-github-down#5]
Is this intentional?

```
$ is-github-down

 🐈  It's up. Go back to work!

$ echo $?
1
```

**Comment by SamVerschueren** [comment]
Apparently yes: https://github.com/sindresorhus/is-github-down/blob/master/cli.js#L14

**Comment by wayneashleyberry** [comment]
Interesting, I'll close this because I think it might largely be a matter of personal preference. For me a non-zero exit code signifies an error occurred.

**Comment by sindresorhus** [comment]
@wayneashleyberry It _is_ an error that GitHub is up. Per its name, it's checking whether GitHub is down. This way you could do something like `$ is-github-down 2>/dev/null || echo "it's up yo"`

**Comment by wayneashleyberry** [comment]
Fair point, just felt a little weird at first getting an error when a site was up haha :)
